### ISSUE TITLE
Can't find in HACS

### ISSUE THREAD

**Issue by HydrelioxGitHub** [koying/openrgb_ha#1]
Hello and thank you very much for your work.
I can't find your repo in "Explore & Add Repositories", do I have to add the github project page through the "custom repository" option in HACS ? Or is there some way to update it to make OpenRGB visible ?

**Comment by koying** [comment]
Hi. Its not yet in HACS. 
Waiting for inclusion...  https://github.com/hacs/default/pull/916

**Comment by koying** [comment]
You can add the repo manually ("Custom repository") in HACS proper, in the meantime

**Comment by HydrelioxGitHub** [comment]
Why the PR has the "blocked" status ?

**Comment by koying** [comment]
No clue what the processes of HACS are...
They seem to include by batch once or twice a month

**Comment by Boren** [comment]
It is now included in HACS and this issue can be closed
