### ISSUE TITLE
Configure setup to get more detailled entities

### ISSUE THREAD

**Issue by HydrelioxGitHub** [koying/openrgb_ha#3]
Is is technically doable to get one entity in HA for each led or zone of the same device ? I don't know if the sdk could do that ...

**Comment by koying** [comment]
I haven't even had a deep look at the OrpenRGB SDK, to be honest.
So far, it's the original PR + fixes for connection issue.

**Comment by FeikoJoosten** [comment]
Had a quick look through some of the SDK providers. And saw that the example in this plugin https://github.com/jath03/openrgb-python (which is now the recommended SDK according to the originally used SDK) should make it pretty straight forward to create devices including all of their zones/leds.

**Comment by FeikoJoosten** [comment]
To come back to this. On [my fork](https://github.com/FeikoJoosten/openrgb_ha) of this repro I have this all working. Still working out some issues. As I'm currently not properly generating unique ids for entities. And I want to see if I can extend zones as well as leds (and make the individual leds disabled by default). Anyway, I'm making progress, however I'm new to this, so I'm not really sure if what I'm doing is the correct approach. 😅

**Comment by FeikoJoosten** [comment]
Hmm yes I see. I probably have some time this evening to add support for zones. Once I have that working the way I intend to I'll setup a PR.

**Comment by FeikoJoosten** [comment]
@HydrelioxGitHub there you go. I've also fixed the unique_id generation https://github.com/koying/openrgb_ha/pull/8
