### ISSUE TITLE
Platform openrgb does not generate unique IDs

### ISSUE THREAD

**Issue by JOHLC** [koying/openrgb_ha#7]
See below for the error that gets logged
Latest version of HA as of today
Latest openrgb version (windows) and this component
 
Possibly relevant HA doc: https://developers.home-assistant.io/docs/entity_registry_index/#unique-id 

````
Logger: homeassistant.components.light
Source: helpers/entity_platform.py:567
Integration: Light (documentation, issues)
First occurred: 1:27:33 PM (74 occurrences)
Last logged: 2:04:03 PM

Platform openrgb does not generate unique IDs. ID openrgb.asus_prime_b360m-a_0 is already used by light.asus_prime_b360m_a_0 - ignoring light.asus_prime_b360m-a_0
````

**Comment by koying** [comment]
Not really sure how it this could happen, it's explicitly checked.

Besides the log entry, does the integration work or not at all? 
Did you install via HACS or other mean?

**Comment by jath03** [comment]
I've noticed the same thing.  The integration works, but there are log messages complaining about unique IDs.  Interestingly, the device it's complaining about for me is also a asus prime motherboard, but the x470 version.
